config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', confirmations: 'confirmations', passwords: 'users/passwords' }

  ActiveAdmin.routes(self)

  mount Member::API => '/api'
  get 'password_resets/create'

  get 'password_resets/edit'

  get 'password_resets/update'

  root to: 'infos#index'

  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
    get 'sign_out', to: 'users/sessions#destroy'
  end

  resources :orders do
    member do
      post 'cancel'
      post 'finished'
      post 'admin_change_status'
      post 'request_refund'
    end
    collection do
      get 'purchase_history'
      post 'manage_on_sale'
    end
  end

  resources :goods do
    member do
      get 'get_price'
    end
  end

  resources :infos do
    collection do
      get 'l_infos'
      post 'reset_my_password'
    end
  end

  resources :admins do
    collection do
      get 'goods'
      get 'notices'
      get 'orders'
      get 'users'
      post 'create_goods'
      get 'expenses'
      get 'edit_user'
      post 'update_user'
      get 'types'
      post 'can_log_in_or_invite'
      get 'edit_user_password'
      post 'update_user_password'
      get 'sale_infos'
    end
  end

  resources :notices do
    collection do
      post 'alert_show'
    end
  end

  resources :special_prices do
    collection do
      get 'user_special_prices'
      get 'goods_special_prices'
      post 'create_or_update'
    end
  end

  resources :levels, only: [:index, :edit, :update]

  resources :system_settings, only: [:update]

  resources :recharge_records, only: [:index, :new] do
    collection do
      get 'call_back'
    end
  end

  resources :deduct_percentages, only: [:index]

  resources :h_set_prices do
    collection do
      post 'create_or_update'
    end
  end

  resources :invites, only: [:index]

  resources :goods_types
end

app/models/special_price.rb
class SpecialPrice < ApplicationRecord
  belongs_to :user
  belongs_to :goods

  def self.seed
    SpecialPrice.create(user_id: 28, goods_id: 3, price: 15, remark: 'HAHAHHAHA')
  end
end

app/controllers/special_prices_controller.rb
class SpecialPricesController < ApplicationController
  before_action :is_admin?

  def index
    @goods = Goods.find(params[:goods_id])
    @special_prices = @goods.special_prices
  end

  def create_or_update
    begin
      goods = Goods.find_by_id(params[:goods_id])
      raise '商品不存在' unless goods.present?
      special_price = SpecialPrice.where(user_id: params[:user_id], goods_id: params[:goods_id]).first
      if special_price.present?
        special_price.update_attribute(:price, params[:price])
      else
        SpecialPrice.create(user_id: params[:user_id], goods_id: params[:goods_id], price: params[:price])
      end
      data = { result: 'success', message: '保存成功' }
    rescue => ex
      data = { result: 'failed', message: ex.message }
    end
    render json: data
  end

  def user_special_prices
    @goods = Goods.all
    @user = User.find(params[:user_id])
    @special_prices = @user.special_prices.includes(:goods)
    @goods = @goods.page(params[:page] || 1).per(10)
  end

  def goods_special_prices
    @goods = Goods.find(params[:goods_id])
    @special_prices = @goods.special_prices.includes(:user)
  end

  def destroy
    begin
      special_price = SpecialPrice.find(params[:id])
      special_price.destroy
      flash[:notice] = '删除成功'
    rescue
      flash[:alert] = '删除失败'
    end
    redirect_to :back
  end

  def edit
    @special_price = SpecialPrice.find(params[:id])
  end

  def update
    begin
      @special_price = SpecialPrice.find(params[:id])
      @special_price.update_attributes(params.require(:special_price).permit(:price, :remark, :user_id, :goods_id))
      flash[:notice] = '修改成功'
    rescue
      flash[:alert] = '修改失败'
    end
    redirect_to action: 'user_special_prices', user_id: params[:special_price][:user_id]
  end
end

app/views/special_prices/edit.html.erb
<%= form_for @special_price, html: {:class => 'form-horizontal'} do |f| %>

<div class="col-md-12">
    <div class="box">
      <div class="box-header with-border">
        <h3 class="box-title">修改特价</h3>
      </div>
      <div class="box-body">
        <div class="form-group">
          <%= f.label :good_name, '业务', class: 'col-sm-1 control-label'%>

          <div class="col-sm-5">
            <%= f.text_field :good_name, value: @special_price.goods.name, class: 'form-control', autocomplete: 'off', readonly: true %>
            <%= f.hidden_field :goods_id %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :user_name, '用户', class: 'col-sm-1 control-label'%>

          <div class="col-sm-5">
            <%= f.text_field :user_name, value: "#{@special_price.user.email}" , autocomplete: 'off', class: 'form-control', readonly: true %>
            <%= f.hidden_field :user_id %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :price, '特价', class: 'col-sm-1 control-label'%>

          <div class="col-sm-5">
            <%= f.text_field :price, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :remark, '备注', class: 'col-sm-1 control-label'%>

          <div class="col-sm-5">
            <%= f.text_area :remark, class: 'form-control', rows: 5, placeholder: '备注信息' %>
          </div>
        </div>
      </div>
      <div class="box-footer clearfix">
        <%= link_to  '放弃修改', user_special_prices_special_prices_path(user_id: @special_price.user.id), class: 'btn btn-default'%>
        <%= f.submit '提交修改', class: 'btn btn-primary' %>
      </div>
    </div>
</div>
<% end %>

app/views/special_prices/goods_special_prices.html.erb
<div class="col-md-12">
  <div class="box">
    <div class="box-header">
      <h3 class="box-title">商品：<%= "#{@goods.name}(ID:#{@goods.id})" %></h3>
    </div>
    <div class="box-body table-responsive no-padding">
      <table class="table table-hover">
        <tr>
          <th>用户</th>
          <th>系统价格</th>
          <th>上级特价</th>
          <th>管理员特价</th>
        </tr>
        <% @special_prices.each do |price| %>
          <tr>
            <% user = price.user %>
            <td><%= user.email %></td>
            <td><%= @goods.get_current_price(user.level_id) %></td>
            <td><%= user.current_goods_h_set_price(@goods.id) %></td>
            <td><%= price.price %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/special_prices/index.html.erb
<div class="col-md-12">
  <div class="box">
    <div class="box-header">
      <h3 class="box-title">业务：<%= @goods.name %></h3>
    </div>
    <div class="box-body table-responsive no-padding">
      <table class="table table-hover">
        <tr>
          <th>用户</th>
          <th>特价</th>
        </tr>
        <% @special_prices.each do |price| %>
          <tr>
            <td><%= "#{price.user.name}(#{price.user.email})" %></td>
            <td><%= price.price %></td>
            <td>
              <%= link_to '修改', edit_good_path(goods.id) %>
              <%= link_to '删除', special_prices_path(goods_id: goods.id) %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
  <button type="button" class="btn btn-default" data-toggle="modal" data-target="#modal-default">
    添加新特价
  </button>
</div>

<div class="modal fade" id="modal-default">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">添加特价</h4>
      </div>
      <%= form_for SpecialPrice.new, html: {:class => 'form-horizontal'} do |f| %>
        <div class="modal-body">
            <div class="box-body">
              <div class="form-group">
                <%= f.label :goods_id, '业务', class: 'col-sm-2 control-label '%>

                <div class="col-sm-10">
                  <%= f.select :goods_id, Goods.all.collect { |g| [ g.name, g.id ] }, {value: @goods.id}, readonly: true, disabled: true, class: 'form-control goods-id' %>
                </div>
              </div>
              <div class="form-group">
                <%= f.label :user_id, '用户', class: 'col-sm-2 control-label '%>

                <div class="col-sm-10">
                  <%= f.select :user_id, User.all.collect { |u| [ u.name, u.id ] }, {}, class: 'form-control goods-id' %>
                </div>
              </div>
              <div class="form-group">
                <%= f.label :price, '特价', class: 'col-sm-2 control-label'%>

                <div class="col-sm-10">
                  <%= f.text_field :price, value: nil, class: 'form-control', placeholder: '单价' %>
                </div>
              </div>
            </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">放弃</button>
          <%= submit_tag '提交', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/special_prices/user_special_prices.html.erb
<div class="col-md-12">
    <div class="box">
      <div class="box-header with-border">
        <h3 class="box-title">下级：<%= @user.name %> 特价</h3>
      </div>
      <div class="box-body">
        <table class="table table-bordered">
          <tr>
            <th>商品</th>
            <th>系统价格</th>
            <th>上级特价</th>
            <th>管理员特价</th>
            <th>操作</th>
          </tr>
          <% @goods.each do |goods| %>
            <tr>
              <% current_goods_special_price_obj = @user.current_goods_special_price_obj(goods.id) %>
              <% h_set_price = @user.current_goods_h_set_price(goods.id) %>
              <% system_price = goods.get_current_price(@user.level_id) %>
              <% special_price = current_goods_special_price_obj.try(:price) %>
              <td><%= goods.name rescue '' %></td>
              <td class="system-price"><%= system_price %></td>
              <td><%= h_set_price %></td>
              <td class="special-price">
                <%= text_field_tag 'special_prices', special_price, class: 'form-control only-bottom-border' %>
              </td>
              <td>
                <a class="btn btn-default save-special-price" goods-id="<%= goods.id %>">保存</a>
                <% if current_goods_special_price_obj.present? %>
                  <%= link_to '清除', special_price_path(current_goods_special_price_obj.id), data: { confirm: '确认清除？'}, method: 'DELETE' %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </table>
      </div>
      <div class="box-footer clearfix">
        <ul class="pagination pagination-sm inline">
          <%= paginate @goods %>
        </ul>
      </div>
    </div>
</div>
<div id='edit-h-set-price'>
</div>

<style>
  .only-bottom-border{
    border-top: none;
    border-right: none;
    border-left: none;
    display: inline-block;
    width: 30%;
  }
  .no-used-price-notice{
    color: red;
  }
</style>
<script type="text/javascript">
    $(".select-goods").select2({
      placeholder: "选择业务",
      allowClear: true
    });
    $('.save-special-price').on('click', function(){
      var current_tr = $(this).parents('tr');
      var system_price = current_tr.find('.system-price').text();
      var special_price = current_tr.find('#special_prices').val();
      special_price = Number(special_price);
      system_price = Number(system_price);
      if (isNaN(special_price)) {
        alert('填写有误！');
        location.reload(true);
        return
      }

      goods_id = $(this).attr('goods-id');
      user_id = "<%= @user.id %>";
      $.ajax({
        url: "<%= create_or_update_special_prices_path %>",
        method: 'post',
        data: {
          goods_id: goods_id,
          user_id: user_id,
          price: special_price
        },
        success: function(data){
          result = data['result'];
          console.log(data);
          if (result == 'success') {
            alert('保存成功');
          } else {
            alert('保存失败');
          }
        },
        error: function(){
          alert('保存失败，请重新提交');
        }
      })
    });
</script>