config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', confirmations: 'confirmations', passwords: 'users/passwords' }

  ActiveAdmin.routes(self)

  mount Member::API => '/api'
  get 'password_resets/create'

  get 'password_resets/edit'

  get 'password_resets/update'

  root to: 'infos#index'

  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
    get 'sign_out', to: 'users/sessions#destroy'
  end

  resources :orders do
    member do
      post 'cancel'
      post 'finished'
      post 'admin_change_status'
      post 'request_refund'
    end
    collection do
      get 'purchase_history'
      post 'manage_on_sale'
    end
  end

  resources :goods do
    member do
      get 'get_price'
    end
  end

  resources :infos do
    collection do
      get 'l_infos'
      post 'reset_my_password'
    end
  end

  resources :admins do
    collection do
      get 'goods'
      get 'notices'
      get 'orders'
      get 'users'
      post 'create_goods'
      get 'expenses'
      get 'edit_user'
      post 'update_user'
      get 'types'
      post 'can_log_in_or_invite'
      get 'edit_user_password'
      post 'update_user_password'
      get 'sale_infos'
    end
  end

  resources :notices do
    collection do
      post 'alert_show'
    end
  end

  resources :special_prices do
    collection do
      get 'user_special_prices'
      get 'goods_special_prices'
      post 'create_or_update'
    end
  end

  resources :levels, only: [:index, :edit, :update]

  resources :system_settings, only: [:update]

  resources :recharge_records, only: [:index, :new] do
    collection do
      get 'call_back'
    end
  end

  resources :deduct_percentages, only: [:index]

  resources :h_set_prices do
    collection do
      post 'create_or_update'
    end
  end

  resources :invites, only: [:index]

  resources :goods_types
end

app/views/admins/_edit_user_modal.html.erb
<div class="modal fade" id="edit-user-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">编辑用户信息</h4>
      </div>
      <%= form_tag update_user_admins_path(), method: 'post', html: {:class => 'form-horizontal'} do %>

        <div class="modal-body">
            <div class="box-body">
              <%= hidden_field_tag :id, @user.id %>
              <div class="form-group">
                <%= label_tag :level_id, '会员等级', class: 'col-sm-2 control-label '%>
                <div class="col-sm-10">
                  <%= text_field_tag :level_id, @user.level_id, class: 'form-control goods-id' %>
                </div>
              </div><br><br>
              <div class="form-group">
                <%= label_tag :current_balance, '账户余额', class: 'col-sm-2 control-label '%>
                <div class="col-sm-3">
                  <%= text_field_tag :balance, @user.balance, readonly: true, class: 'form-control current-balance' %>
                </div>
                <div class="col-sm-1 operater">
                  +
                </div>
                <div class="col-sm-3">
                  <%= text_field_tag :balance, 0, class: 'form-control change-balance' %>
                </div>
                <div class="col-sm-1 operater">
                  =
                </div>
                <div class="col-sm-3">
                  <%= text_field_tag :target_balance, @user.balance, readonly: true, class: 'form-control target-balance' %>
                </div>
              </div><br><br>
            </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">放弃</button>
          <%= submit_tag '提交', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<style>
  .operater{
    padding: 0px;
    padding-top: 4px;
    width: 22px;
    text-align: center;
  }
</style>

<script>
$(document).ready(function() {
  current_balance = $('.current-balance').val();
  $('.change-balance').bind('input propertychange', function(){
      change_balance = $(this).val();
      target_balance = parseFloat(current_balance) + parseInt(change_balance);
      if(isNaN(target_balance)){
        $('.target-balance').val('输入有误');
      }else {
        $('.target-balance').val(target_balance);
      }
  });
});
</script>

app/views/admins/_edit_user_password_modal.html.erb
<div class="modal fade" id="edit-user-password-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">重置用户：<%= @user.name%> 密码</h4>
      </div>
      <%= form_tag update_user_password_admins_path, method: 'post', html: {:class => 'form-horizontal'} do %>
        <div class="modal-body">
            <div class="box-body">
              <%= hidden_field_tag :id, @user.id %>
              <div class="form-group">
                <div class="col-sm-10">
                  <%= password_field_tag :password, nil, class: 'form-control', placeholder: '新密码' %>
                </div>
              </div></br>
              <div class="form-group">
                <div class="col-sm-10">
                  <%= password_field_tag :password_confirmation, nil, class: 'form-control', placeholder: '密码确认' %>
                </div>
              </div>
            </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">放弃</button>
          <%= submit_tag '提交', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admins/_expenses_search_form.html.erb
<div class="col-md-12">
  <div class="box">
    <%= form_tag expenses_admins_path, method: 'get' do %>
      <div class="box-body">
        <div class="form-group">
          <div class="col-xs-2">
            <%= label_tag '用户' %>
            <%= select_tag :id, options_from_collection_for_select(User.all, 'id', 'email', params['id']), include_blank: true, class: 'form-control single-select' %>
          </div>
          <div class="col-xs-3">
            <label>自定义时间:</label>

            <div class="input-group">
              <div class="input-group-addon">
                <i class="fa fa-calendar"></i>
              </div>
              <%= text_field_tag :start_time, params[:start_time], class: 'form-control pull-right start-time', placeholder: '开始时间' %>
            </div>
          </div>
          <div class="col-xs-3">
            <label> </label>

            <div class="input-group make-line">
              <div class="input-group-addon">
                <i class="fa fa-calendar"></i>
              </div>
              <%= text_field_tag :end_time, params[:end_time], class: 'form-control pull-right start-time', placeholder: '结束时间' %>
            </div>
          </div>
          <div class="col-xs-2">
            <label ></label>
            <%= submit_tag '查询', class: 'btn btn-block btn-primary btn-flat make-line'%>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<script type="text/javascript">
    $(".start-time").datetimepicker({format: 'yyyy-mm-dd hh:ii'});
    $(".end-time").datetimepicker({format: 'yyyy-mm-dd hh:ii'});

    $(".single-select").select2({
      placeholder: "选择用户",
      allowClear: true
    });
</script>

app/views/admins/_goods_search_form.html.erb
<div class="col-md-12">
  <div class="box">
    <%= form_tag goods_admins_path, method: 'get' do %>
      <div class="box-body">
        <div class="form-group">
          <div class="col-xs-2">
            <%= label_tag '分类' %>
            <%= select_tag :goods_type_id, options_from_collection_for_select(GoodsType.all, 'id', 'name', params['goods_type_id']), include_blank: true, class: 'form-control single-select-type' %>
          </div>
          <div class="col-xs-2">
            <%= label_tag '业务' %>
            <%= select_tag :goods_id, options_from_collection_for_select(Goods.all, 'id', 'name', params['goods_id']), include_blank: true, class: 'form-control single-select' %>
          </div>
          <div class="col-xs-2">
            <label ></label>
            <%= submit_tag '查询', class: 'btn btn-block btn-primary btn-flat make-line'%>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<script type="text/javascript">
    $(".single-select-type").select2({
      placeholder: "选择分类",
      allowClear: true
    });
    $(".single-select").select2({
      placeholder: "选择业务",
      allowClear: true
    });
</script>

app/views/admins/_operation_link.html.erb
<% if status == 'Waiting' %>
  <%= link_to '标记为处理中', admin_change_status_order_path(order_id, status: 'Dealing'), method: 'post' %>
  <%= link_to '退款', admin_change_status_order_path(order_id, status: 'Refund'), data: { confirm: '确定退款？' }, method: 'post' %>
<% elsif status == 'Dealing' %>
  <%= link_to '标记为完成', admin_change_status_order_path(order_id, status: 'Finished'), method: 'post' %>
  <%= link_to '退款', admin_change_status_order_path(order_id, status: 'Refund'), method: 'post', data: { confirm: '确定退款？'} %>
<% elsif status == 'InRefund' %>
  <%= link_to '退款', admin_change_status_order_path(order_id, status: 'Refund'), method: 'post', data: { confirm: '确定退款？'} %>
<% elsif status == 'Finished' %>
  <%#= link_to '隐藏', admin_change_status_order_path(order_id, status: 'Hided'), method: 'post' %>
  已完成
<% end %>

app/views/admins/_order_controll_link.html.erb
<%= link_to '待处理订单', orders_admins_path(status: 'Waiting'), class: "btn  btn-flat #{current_status_order?('Waiting')}" %>
<%= link_to '处理中订单', orders_admins_path(status: 'Dealing'), class: "btn  btn-flat #{current_status_order?('Dealing')}"%>
<%= link_to '已退款订单', orders_admins_path(status: 'Refund'), class: "btn  btn-flat #{current_status_order?('Refund')}" %>
<%= link_to '已完成订单', orders_admins_path(status: 'Finished'), class: "btn  btn-flat #{current_status_order?('Finished')}" %>
<%= link_to '待退款订单', orders_admins_path(status: 'InRefund'), class: "btn  btn-flat #{current_status_order?('InRefund')}" %>
<%#= link_to '退款失败订单', orders_admins_path(status: 'CancelFailed'), class: "btn  btn-flat #{current_status_order?('CancelFailed')}" %>

app/views/admins/_order_search_form.html.erb
<div class="col-md-12">
  <div class="box">
    <%= form_tag orders_admins_path, method: 'get' do %>
      <div class="box-body">
        <div class="form-group">
          <%= hidden_field_tag :status, params[:status] %>
          <div class="col-xs-2">
            <%= label_tag '用户' %>
            <%= select_tag :user_id, options_from_collection_for_select(User.all, 'id', 'email', params['user_id']), include_blank: true, class: 'form-control select-user' %>
          </div>

          <div class="col-xs-2">
            <%= label_tag '业务类型' %>
            <%= select_tag :goods_id, options_from_collection_for_select(Goods.all, 'id', 'name', params['goods_id']), include_blank: true, class: 'form-control single-select' %>
          </div>
          <div class="col-xs-2">
            <label for="exampleInputEmail1">下单账号</label>
            <%= text_field_tag :account, params['account'], class: 'form-control', placeholder: '下单账号' %>
          </div>
          <div class="col-xs-2">
            <label for="exampleInputEmail1">备注信息</label>
            <%= text_field_tag :remark, params['remark'], class: 'form-control', placeholder: '备注信息'%>
          </div>
          <div class="col-xs-2">
            <label ></label>
            <%= submit_tag '查询', class: 'btn btn-block btn-primary btn-flat make-line'%>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<script type="text/javascript">
    $(".select-user").select2({
      placeholder: "选择用户",
      allowClear: true
    });
    $(".single-select").select2({
      placeholder: "选择业务",
      allowClear: true
    });
</script>

app/views/admins/_sale_infos_search_form.html.erb
<div class="col-md-12">
  <div class="box">
    <%= form_tag sale_infos_admins_path, method: 'get' do %>
      <div class="box-body">
        <div class="form-group">
          <div class="col-xs-2">
            <%= label_tag '商品' %>
            <%= select_tag :goods_id, options_from_collection_for_select(Goods.all, 'id', 'name', params['goods_id']), include_blank: true, class: 'form-control select-goods' %>
          </div>
          <div class="col-xs-3">
            <label>自定义时间:</label>

            <div class="input-group">
              <div class="input-group-addon">
                <i class="fa fa-calendar"></i>
              </div>
              <%= text_field_tag :start_time, params[:start_time], class: 'form-control pull-right start-time', placeholder: '开始时间' %>
            </div>
          </div>
          <div class="col-xs-3">
            <label> </label>

            <div class="input-group make-line">
              <div class="input-group-addon">
                <i class="fa fa-calendar"></i>
              </div>
              <%= text_field_tag :end_time, params[:end_time], class: 'form-control pull-right start-time', placeholder: '结束时间' %>
            </div>
          </div>
          <div class="col-xs-2">
            <label ></label>
            <%= submit_tag '查询', class: 'btn btn-block btn-primary btn-flat make-line'%>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  $(".start-time").datetimepicker({format: 'yyyy-mm-dd hh:ii'});
  $(".end-time").datetimepicker({format: 'yyyy-mm-dd hh:ii'});

    $(".select-goods").select2({
      placeholder: "选择业务",
      allowClear: true
    });
</script>

app/views/admins/edit_user.js.erb
$('#add_edit_user_modal').html("<%= escape_javascript(render 'edit_user_modal') %>")
$("#edit-user-modal").modal("show")

app/views/admins/goods.html.erb
<div class="col-md-12 controll-button">
  <%= render 'controll_button' %>
</div>

<%= render 'goods_search_form' %>

<div class="col-md-12">
  <div class="box">
    <div class="box-header">
      <h3 class="box-title">业务信息</h3>
    </div>
    <div class="box-body table-responsive no-padding">
      <table class="table table-hover">
        <tr>
          <th>#</th>
          <th>分类</th>
          <th>业务</th>
          <th>说明</th>
          <th>LV1价格</th>
          <th>LV2价格</th>
          <th>LV3价格</th>
          <th>LV4价格</th>
          <th>下架</th>
          <th>管理</th>
        </tr>
        <% @goods.each do |goods| %>
          <tr>
            <td><%= goods.id %></td>
            <td><%= goods.goods_type.try(:name) %></td>
            <td><%= goods.name %></td>
            <td>
              <%= goods.remark %>
            </td>
            <td><%= price_to_humam(goods.get_current_price(1)) %></td>
            <td><%= price_to_humam(goods.get_current_price(2)) %></td>
            <td><%= price_to_humam(goods.get_current_price(3)) %></td>
            <td><%= price_to_humam(goods.get_current_price(4)) %></td>
            <td>
              <% if goods.on_sale %>
                <input type="checkbox" class="manage-on-sale" goods-id="<%= goods.id %>" checked data-toggle="toggle" data-on="已上架" data-off='已下架' data-style="ios" data-onstyle="success" data-offstyle="danger">
              <% else %>
                <input type="checkbox" class="manage-on-sale" goods-id="<%= goods.id %>" data-toggle="toggle" data-on="已上架" data-off='已下架' data-style="ios" data-onstyle="success" data-offstyle="danger">
              <% end %>
            </td>
            <td>
              <%= link_to '修改', edit_good_path(goods.id) %>
              <%= link_to '特价信息', goods_special_prices_special_prices_path(goods_id: goods.id) %>
              <%= link_to '删除', good_path(goods.id), method: 'DELETE', data: { confirm: '确定删除？' } %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
    <div class="box-footer clearfix">
      <ul class="pagination pagination-sm inline">
        <%= paginate @goods %>
      </ul>
    </div>
  </div>
  <button type="button" class="btn btn-default" data-toggle="modal" data-target="#modal-default">
    添加新业务
  </button>
</div>

<div class="modal fade" id="modal-default">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">新业务</h4>
      </div>
      <%= form_tag goods_path, method: 'post', html: {:class => 'form-horizontal'} do %>

        <div class="modal-body">
            <div class="box-body">
              <div class="form-group">
                <%= label_tag :type_id, '分类', class: 'col-sm-2 control-label '%>
                <div class="col-sm-10">
                  <%= select_tag :type_id, options_from_collection_for_select(GoodsType.all, 'id', 'name', params['type_id']), placeholder: '选择分类', class: 'form-control select-goods-type' %>
                </div>
              </div><br><br>
              <div class="form-group">
                <%= label_tag :name, '业务', class: 'col-sm-2 control-label '%>

                <div class="col-sm-10">
                  <%= text_field_tag :name, nil, class: 'form-control goods-id', placeholder: '业务名称' %>
                </div>
              </div><br><br>
              <div class="form-group">
                <%= label_tag :price, '单价', class: 'col-sm-2 control-label'%>

                <div class="col-sm-10">
                  <%= text_field_tag :price, nil, class: 'form-control', placeholder: '四个单价，以空格隔开，如：33 23 13 3' %>
                </div>
              </div><br><br>
              <div class="form-group">
                <%= label_tag :remark, '业务说明', class: 'col-sm-2 control-label'%>

                <div class="col-sm-10">
                  <%= text_field_tag :remark, nil, class: 'form-control', placeholder: '业务说明' %>
                </div>
              </div>
            </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">放弃</button>
          <%= submit_tag '提交', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<style>
  .goods-type-info{
    margin-top: 30px;
  }

  .toggle.ios, .toggle-on.ios, .toggle-off.ios { border-radius: 20px; }
  .toggle.ios .toggle-handle { border-radius: 20px; }
</style>

<script>
  $('.manage-on-sale').change(function(){
    state = $(this).prop('checked');
    id = $(this).attr('goods-id');
    $.ajax({
      url: "<%= manage_on_sale_orders_path %>",
      method: 'post',
      type: 'json',
      data: {
        id: id,
        on_sale: state
      }
    })
  });
</script>

app/views/admins/notices.html.erb
<div class="col-md-12 controll-button">
  <%= render 'controll_button' %>
</div>

<div class="col-md-12">
  <div class="box">
    <div class="box-header">
      <h3 class="box-title">系统公告</h3>
    </div>
    <div class="box-body table-responsive no-padding">
      <table class="table table-hover">
        <tr>
          <th>标题</th>
          <th>内容</th>
          <th>发布时间</th>
          <th>弹窗</th>
          <th>管理</th>
        </tr>
        <% @notices.each do |notice| %>
          <tr>
            <td><%= notice.title %></td>
            <td><%= notice.content %></td>
            <td><%= notice.updated_at.strftime("%Y-%m-%d %H:%M:%S") %></td>
            <td>
              <% if notice.is_alert %>
                <input type="checkbox" class="notice-alert-show" notice-id="<%= notice.id %>" checked data-toggle="toggle" data-on="弹窗" data-off='不弹窗' data-style="ios" data-onstyle="success" data-offstyle="danger">
              <% else %>
                <input type="checkbox" class="notice-alert-show" notice-id="<%= notice.id %>" data-toggle="toggle" data-on="弹窗" data-off='不弹窗' data-style="ios" data-onstyle="success" data-offstyle="danger">
              <% end %>
            </td>
            <td>
              <%= link_to '编辑', edit_notice_path(notice.id),remote: true  %>
              <%= link_to '删除', notice_path(notice.id), method: 'DELETE',  data: { confirm: '确定删除？' } %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
  <div id="add_edit_notice_modal"></div>
  <button type="button" class="btn btn-default" data-toggle="modal" data-target="#modal-default">
    发布公告
  </button>
</div>

<div class="col-md-12">
  <hr>
  <div class="form-group">
    <% system_setting = SystemSetting.first %>
    <% if system_setting.can_sigin_up %>
      <input type="checkbox" id="toggle-sigin-up" checked data-toggle="toggle" data-on="可注册" data-off="不可注册" data-onstyle="success" data-offstyle="danger">
    <% else %>
      <input type="checkbox" id="toggle-sigin-up" data-toggle="toggle" data-on="可注册" data-off="不可注册" data-onstyle="success" data-offstyle="danger">
    <% end %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <% if system_setting.can_recharge %>
      <input type="checkbox" id="toggle-recharge" checked data-toggle="toggle" data-on="可充值" data-off="不可充值" data-onstyle="success" data-offstyle="danger">
    <% else %>
      <input type="checkbox" id="toggle-recharge" data-toggle="toggle" data-on="可充值" data-off="不可充值" data-onstyle="success" data-offstyle="danger">
    <% end %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <% if system_setting.need_invitation_code %>
      <input type="checkbox" id="toggle-need-invitation-code" checked data-toggle="toggle" data-on="必须填写邀请码" data-off="不需要邀请码" data-onstyle="success" data-offstyle="danger">
    <% else %>
      <input type="checkbox" id="toggle-need-invitation-code" data-toggle="toggle" data-on="必须填写邀请码" data-off="不需要邀请码" data-onstyle="success" data-offstyle="danger">
    <% end %>
  </div>
</div>

<div class="modal fade" id="modal-default">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">发布公告</h4>
      </div>
      <%= form_for Notice.new, method: 'post', html: {:class => 'form-horizontal'} do |f| %>

        <div class="modal-body">
            <div class="box-body">
              <div class="form-group">
                <label class="col-sm-2 control-label">标题</label>
                <div class="col-sm-10">
                  <%= f.text_field :title, class: 'form-control', placeholder: '标题' %>
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-2 control-label">公告</label>
                <div class="col-sm-10">
                  <%= f.text_area :content, class: 'form-control', rows: 5, placeholder: '内容' %>
                </div>
              </div>
            </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">放弃</button>
          <%= f.submit '提交', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<style>
  .toggle.ios, .toggle-on.ios, .toggle-off.ios { border-radius: 20px; }
  .toggle.ios .toggle-handle { border-radius: 20px; }
</style>

<script>
  $('.notice-alert-show').change(function(){
    state = $(this).prop('checked');
    id = $(this).attr('notice-id');

    $.ajax({
      url: "<%= alert_show_notices_path %>",
      method: 'post',
      type: 'json',
      data: {
        id: id,
        is_alert: state
      }
    })
  });

  $('#toggle-sigin-up').change(function(){
    state = $(this).prop('checked');
    $.ajax({
      url: "<%= system_setting_path(1) %>",
      method: 'put',
      type: 'json',
      data: {
        change_info: { can_sigin_up: state }
      }
    })
  });

  $('#toggle-recharge').change(function(){
    state = $(this).prop('checked');
    $.ajax({
      url: "<%= system_setting_path(1) %>",
      method: 'put',
      type: 'json',
      data: {
        change_info: { can_recharge: state }
      }
    })
  });

  $('#toggle-need-invitation-code').change(function(){
    state = $(this).prop('checked');
    $.ajax({
      url: "<%= system_setting_path(1) %>",
      method: 'put',
      type: 'json',
      data: {
        change_info: { need_invitation_code: state }
      }
    })
  });
</script>

app/views/admins/users.html.erb
<div class="col-md-12 controll-button">
  <%= render 'controll_button' %>
</div>

<%= render 'user_search_form'%>

<div class="col-md-12">
  <div class="box">
    <div class="box-header">
      <h3 class="box-title">会员信息</h3>
    </div>
    <div class="box-body table-responsive no-padding">
      <table class="table table-hover">
        <tr>
          <th>ID</th>
          <th>邮箱</th>
          <th>账户余额</th>
          <th>等级</th>
          <th>下级会员数</th>
          <th>订单总数</th>
          <th>消费总额</th>
          <th>邀请码</th>
          <th>可登录</th>
          <th>可邀请下级</th>
          <th>管理</th>
        </tr>
        <% @users.each do |user| %>
          <% cache user do %>
            <tr>
            <td><%= user.id %></td>
            <td><%= user.email %></td>
            <th><%= user.balance %></th>
            <td><%= user.level_id %></td>
            <td><%= user.low_level_users.count %></td>
            <td><%= user.orders.count %></td>
            <td><%= user.total_spend %></td>
            <td><%= user.invitation_code_in_word %></td>
            <td>
              <% if user.id != 1266 %>
                <% if user.active %>
                  <input type="checkbox" class="can-login" user-id="<%= user.id %>" checked data-toggle="toggle" data-on="可登录" data-off='不可登录' data-style="ios" data-onstyle="success" data-offstyle="danger">
                <% else %>
                  <input type="checkbox" class="can-login" user-id="<%= user.id %>" data-toggle="toggle" data-on="可登录" data-off='不可登录' data-style="ios" data-onstyle="success" data-offstyle="danger">
                <% end %>
              <% else %>
                不要皮！
              <% end %>
            </td>
            <td>
              <% if user.level_id == 1 %>
                不可邀请会员
              <% elsif user.can_invite %>
                <input type="checkbox" class="can-invite" user-id="<%= user.id %>" checked data-toggle="toggle" data-on="可邀请下级" data-off='不可邀请下级' data-style="ios" data-onstyle="success" data-offstyle="danger">
              <% else %>
                <input type="checkbox" class="can-invite" user-id="<%= user.id %>" data-toggle="toggle" data-on="可邀请下级" data-off='不可邀请下级' data-style="ios" data-onstyle="success" data-offstyle="danger">
              <% end %>
            </td>
            <td>
              <%= link_to '特价', user_special_prices_special_prices_path(user_id: user.id) %>
              <%= link_to '编辑', edit_user_admins_path(user_id: user.id), remote: true  %>
              <%= link_to '密码重置', edit_user_password_admins_path(user_id: user.id), remote: true  %>
            </td>
          </tr>
          <% end %>
        <% end %>
      </table>
    </div>
    <div class="box-footer clearfix">
      <ul class="pagination pagination-sm inline">
        <%= paginate @users %>
      </ul>
    </div>
  </div>
  <div id="add_edit_user_modal"></div>
  <div id="add_edit_user_password_modal"></div>
  <%= link_to '会员级别规则', levels_path %>
</div>

<style>
  .toggle.ios, .toggle-on.ios, .toggle-off.ios { border-radius: 20px; }
  .toggle.ios .toggle-handle { border-radius: 20px; }
</style>

<script>
  $('.can-login').change(function(e){
    id = $(this).attr('user-id');
    state = $(this).prop('checked');
    if (id == 1265) {
      e.preventDefault()
      alert('您好，为了方便其他用户登陆，请不要禁止 fortest 登陆');
      return false;
    }
    $.ajax({
      url: "<%= can_log_in_or_invite_admins_path %>",
      method: 'post',
      type: 'json',
      data: {
        id: id,
        change_info: { active: state }
      }
    })
  });

  $('.can-invite').change(function(){
    state = $(this).prop('checked');
    id = $(this).attr('user-id');
    $.ajax({
      url: "<%= can_log_in_or_invite_admins_path %>",
      method: 'post',
      type: 'json',
      data: {
        id: id,
        change_info: { can_invite: state }
      }
    })
  });
</script>