config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', confirmations: 'confirmations', passwords: 'users/passwords' }

  ActiveAdmin.routes(self)

  mount Member::API => '/api'
  get 'password_resets/create'

  get 'password_resets/edit'

  get 'password_resets/update'

  root to: 'infos#index'

  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
    get 'sign_out', to: 'users/sessions#destroy'
  end

  resources :orders do
    member do
      post 'cancel'
      post 'finished'
      post 'admin_change_status'
      post 'request_refund'
    end
    collection do
      get 'purchase_history'
      post 'manage_on_sale'
    end
  end

  resources :goods do
    member do
      get 'get_price'
    end
  end

  resources :infos do
    collection do
      get 'l_infos'
      post 'reset_my_password'
    end
  end

  resources :admins do
    collection do
      get 'goods'
      get 'notices'
      get 'orders'
      get 'users'
      post 'create_goods'
      get 'expenses'
      get 'edit_user'
      post 'update_user'
      get 'types'
      post 'can_log_in_or_invite'
      get 'edit_user_password'
      post 'update_user_password'
      get 'sale_infos'
    end
  end

  resources :notices do
    collection do
      post 'alert_show'
    end
  end

  resources :special_prices do
    collection do
      get 'user_special_prices'
      get 'goods_special_prices'
      post 'create_or_update'
    end
  end

  resources :levels, only: [:index, :edit, :update]

  resources :system_settings, only: [:update]

  resources :recharge_records, only: [:index, :new] do
    collection do
      get 'call_back'
    end
  end

  resources :deduct_percentages, only: [:index]

  resources :h_set_prices do
    collection do
      post 'create_or_update'
    end
  end

  resources :invites, only: [:index]

  resources :goods_types
end

app/controllers/goods_types_controller.rb
class GoodsTypesController < ApplicationController
  def index
    @types = GoodsType.all
  end

  def destroy
    type = GoodsType.find_by_id(params[:id])
    return redirect_to :back, alert: '无法删除' if Goods.exists?(goods_type_id: params[:id])
    type.destroy
    redirect_to :back, notice: '删除成功'
  end

  def new
    @type = GoodsType.new
    respond_to do |format|
      format.js
    end
  end

  def create
    type = GoodsType.find_by_name(params[:name])
    return redirect_to :back, alert: '分类已经存在' if type.present?
    GoodsType.create(name: params[:name])
    redirect_to :back, notice: '创建成功'
  end

  def edit
    @type = GoodsType.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  def update
    begin
      @type = GoodsType.find_by_id(params[:id])
      raise '分类信息不存在' if @type.nil?

      exit_type = GoodsType.find_by_name(params[:name])
      raise '分类已经存在'  if exit_type.present? && exit_type.id != @type.id

      @type.update_attribute(:name, params[:name])
      return redirect_to :back, notice: '编辑成功'
    rescue => ex
      return redirect_to :back, alert: ex.message
    end
  end

end

app/views/goods_types/_edit_modal.html.erb
<div class="modal fade" id="edit-goods-type-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">编辑分类</h4>
      </div>
      <%= form_tag goods_type_path, method: 'PUT', html: {:class => 'form-horizontal'} do %>

        <div class="modal-body">
            <div class="box-body">
              <div class="form-group">
                <%= hidden_field_tag :id, @type.id %>
                <%= label_tag :name, '分类', class: 'col-sm-2 control-label '%>

                <div class="col-sm-10">
                  <%= text_field_tag :name, @type.name, class: 'form-control goods-id', placeholder: '业务名称' %>
                </div>
              </div><br><br>
            </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">放弃</button>
          <%= submit_tag '提交', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/goods_types/edit.js.erb
$('#add_edit_goods_type_modal').html("<%= escape_javascript(render 'edit_modal') %>")
$("#edit-goods-type-modal").modal("show")