config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', confirmations: 'confirmations', passwords: 'users/passwords' }

  ActiveAdmin.routes(self)

  mount Member::API => '/api'
  get 'password_resets/create'

  get 'password_resets/edit'

  get 'password_resets/update'

  root to: 'infos#index'

  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
    get 'sign_out', to: 'users/sessions#destroy'
  end

  resources :orders do
    member do
      post 'cancel'
      post 'finished'
      post 'admin_change_status'
      post 'request_refund'
    end
    collection do
      get 'purchase_history'
      post 'manage_on_sale'
    end
  end

  resources :goods do
    member do
      get 'get_price'
    end
  end

  resources :infos do
    collection do
      get 'l_infos'
      post 'reset_my_password'
    end
  end

  resources :admins do
    collection do
      get 'goods'
      get 'notices'
      get 'orders'
      get 'users'
      post 'create_goods'
      get 'expenses'
      get 'edit_user'
      post 'update_user'
      get 'types'
      post 'can_log_in_or_invite'
      get 'edit_user_password'
      post 'update_user_password'
      get 'sale_infos'
    end
  end

  resources :notices do
    collection do
      post 'alert_show'
    end
  end

  resources :special_prices do
    collection do
      get 'user_special_prices'
      get 'goods_special_prices'
      post 'create_or_update'
    end
  end

  resources :levels, only: [:index, :edit, :update]

  resources :system_settings, only: [:update]

  resources :recharge_records, only: [:index, :new] do
    collection do
      get 'call_back'
    end
  end

  resources :deduct_percentages, only: [:index]

  resources :h_set_prices do
    collection do
      post 'create_or_update'
    end
  end

  resources :invites, only: [:index]

  resources :goods_types
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
  def index
    @goods = Goods.where(on_sale: true)
    @total_spend = current_user.total_spend
    @orders_count = current_user.orders.count
    @notices = Notice.all
    @notices_alert = Notice.where(is_alert: true)
    @has_alert = Notice.exists?(is_alert: true)
  end

  def l_infos
    @l_users = current_user.low_level_users
  end

  def reset_my_password
    begin
      if current_user.email == 'fortest@mms.com'
        flash[:notice] = '抱歉，不允许修改 fortest 的密码'
        return redirect_to :back
      end
      valid = current_user.valid_password?(params[:current_pasword])
      raise '当前密码不正确' unless valid
      raise '密码不能为空' unless params[:password].present?
      raise '两次输入密码不一致' unless params[:password] == params[:password_confirmation]
      raise '密码不能少于六位' unless params[:password].length >= 6

      current_user.password = params[:password]
      current_user.password_confirmation = params[:password_confirmation]
      current_user.md5_password = Digest::MD5.hexdigest(current_user.email + 'WoNiMaDeYa' + Time.now.to_s)
      current_user.save!

      flash[:notice] = '密码更改成功，请用新密码登录'
      return redirect_to new_user_session_path
    rescue => ex
      flash[:alert] = ex.message
    end
    redirect_to :back
  end
end

app/helpers/infos_helper.rb
module InfosHelper
  def current_price(level_id)
    level_id == current_user.level_id ?  "bg-aqua" : ''
  end
end

app/views/infos/index.html.erb
<div class="col-md-12" style="margin-bottom: 20px;">
  <div class="row">
      <div class="col-md-4 col-sm-6 col-xs-12">
        <div class="info-box">
          <span class="info-box-icon bg-red"><i class="fa fa-user-o" aria-hidden="true"></i></span>
          <div class="info-box-content">
            <div class="infos">昵称：<%= current_user.name %></div>
            <div class="infos">邮箱：<%= current_user.email %></div>
            <div class="infos">
              <a  href='#' data-toggle="modal" data-target="#edit-password-default">修改密码</a>
            </div>
          </div>
        </div>
      </div>

      <div class="col-md-4 col-sm-6 col-xs-12">
          <div class="info-box">
            <span class="info-box-icon bg-yellow"><i class="fa fa-money" aria-hidden="true"></i></span>

            <div class="info-box-content">
              <div class="infos">余额：<%= current_user.balance %></div>
              <div class="infos">提成：<%= current_user.deduct_percentage %></div>
              <div class="infos">
                <%= link_to '账户充值', new_recharge_record_path %>
              </div>
            </div>
            <!-- /.info-box-content -->
          </div>
          <!-- /.info-box -->
      </div>

      <div class="col-md-4 col-sm-6 col-xs-12">
          <div class="info-box">
            <span class="info-box-icon  bg-aqua"><i class="fa fa-shopping-cart" aria-hidden="true"></i></span>

            <div class="info-box-content">
              <div class="infos">订单数：<%= @orders_count %></div>
              <div class="infos">总消费：<%= @total_spend  || 0 %></div>
              <div class="infos">
                <%= link_to '订单中心', orders_path %>
              </div>
            </div>
            <!-- /.info-box-content -->
          </div>
          <!-- /.info-box -->
      </div>
      </div>
</div>

<div class="col-md-12">
  <div class="box box-primary">
    <div class="box-header">
      <h3 class="box-title"></h3>
    </div>
    <div class="form-horizontal">
      <div class="box-body">
        <div class="col-md-6">
          <div class="form-group">
            <label class="col-sm-3 control-label">个人邀请码</label>
            <div class="col-sm-9padding-left-none">
              <span class="form-control border-none"> <%= current_user.invitation_code_in_word %> </span>
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-3 control-label">上级邀请码</label>
            <div class="col-sm-9 padding-left-none">
              <span class="form-control border-none"> <%= current_user.h_invitation_code %> </span>
            </div>
          </div>

        </div>
        <div class="col-md-6">
          <div class="form-group">
          </div>
          <div class="form-group">
            <label class="col-sm-3 control-label">Api认证</label>
            <div class="col-sm-9 padding-left-none">
              <span class="form-control border-none md5-password-area dispaly-none">
                <input id="api-authen" value="<%= current_user.md5_password %>" class="clipboard_input" readonly>
                <button class="btn btn-default clipboard_button" data-clipboard-target="#api-authen">
                  复制
                </button>
                <span class="hide-md5-password">
                  <i class="fa fa-eye-slash" aria-hidden="true"></i>
                </span>
              </span>
              <span class="form-control border-none show-md5-password">
                <i class="fa fa-eye" aria-hidden="true"></i>
              </span>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-3 control-label">邀请下级</label>
            <div class="col-sm-9 padding-left-none">
              <span class="form-control border-none">
                <input id="foo" value="<%= invit_link_in_world %>" class="clipboard_input" readonly>
                <button class="btn btn-default clipboard_button" data-clipboard-target="#foo">
                  复制
                </button>
              </span>
            </div>
          </div>
        </div>
    </div>
    </div>
  </div>
</div>

<div class="modal fade" id="edit-password-default">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">修改密码</h4>
      </div>
      <%= form_tag reset_my_password_infos_path, method: 'post' , html: {:class => 'form-horizontal'} do %>
        <div class="modal-body">
            <div class="box-body">
              <div class="form-group">
                <div class="col-sm-10">
                  <%= password_field_tag :current_pasword, nil, class: 'form-control', placeholder: '当前密码' %>
                </div>
              </div><br>
              <div class="form-group">
                <div class="col-sm-10">
                  <%= password_field_tag :password, nil, class: 'form-control', placeholder: '新密码' %>
                </div>
              </div></br>
              <div class="form-group">
                <div class="col-sm-10">
                  <%= password_field_tag :password_confirmation, nil, class: 'form-control', placeholder: '密码确认' %>
                </div>
              </div>
            </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">放弃</button>
          <%= submit_tag '提交', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="modal fade" id="alert-notice">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">系统消息</h4>
      </div>
        <div class="modal-body">
          <div class="box-body table-responsive no-padding">
            <table class="table table-hover">
              <% @notices_alert.each do |notice| %>
                <tr>
                  <td class="notice-item"> <%= sanitize notice.content.gsub(/\r\n/, '<br>') %></td>
                </tr>
              <% end %>
            </table>
          </div>
        </div>
        <div class="modal-footer text-center">
          <button type="button" class="btn btn-default" data-dismiss="modal">知道了</button>
        </div>
    </div>
  </div>
</div>
<%  if @notices.present? %>
  <div class="col-md-12">
    <div class="box box-success">
    <div class="box-header with-border">
      <h3 class="box-title">系统公告！</h3>

      <div class="box-tools pull-right">
        <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
      </div>
    </div>
    <div class="box-body notice-all">
      <ul class="notice-item">
        <% @notices.each do |notice| %>
          <li class="notice-title">
            <i class="fa fa-angle-right" aria-hidden="true"></i>
            <%= notice.title %>
          </li>
          <div class="notice-content dispaly-none">
            <%= sanitize notice.content.gsub(/\r\n/, '<br>') %>
          </div>
        <% end %>
      </ul>
    </div>
  </div>
  <div id="show_notice"></div>
</div>
<% end %>


<style>
  .notice_time{
    display: inline-block;
    margin-right: 0px;
    float: right;
  }

  .clipboard_input{
    width: 335px;
  }

  .clipboard_button{
    background-color: #FFF;
    padding: 1px 2px;
  }

  .clipboard_image{
    width: 20px !important;
  }

  .show-md5-password,
  .hide-md5-password{
    cursor: pointer;
  }

  .dispaly-none{
    display: none;
  }

  ul.notice-item .notice-content{
    background: #f6f6f6;
    padding: 10px 0px 10px 8px;
    margin-left: 13px;
  }

  ul{
    padding-left: 0px;
  }

  ul li.notice-title{
    list-style-type: none;
    padding: 5px 0px 5px 0px;
    cursor: pointer;
  }

  .notice-all{
    padding-left: 30px;
  }

  .infos{
    font-size: 18px;
  }
</style>

<script>
  $('.notice-title').on('click', function(){
    $('ul.notice-item .notice-content').addClass('dispaly-none');
    $('li.notice-title i').removeClass('fa-angle-down');
    $('li.notice-title i').addClass('fa-angle-right');

    var notice_content = $(this).next('.notice-content');
    var current_is_opened = notice_content.hasClass('opened')

    $('ul.notice-item .notice-content').removeClass('opened');

    if(current_is_opened){
      notice_content.addClass('opened');
    }

    var icon = $(this).find('i')

    if(notice_content.hasClass('opened')){
      icon.addClass('fa-angle-right');
      icon.removeClass('fa-angle-down');
      notice_content.addClass('dispaly-none');
      notice_content.removeClass('opened');
    }else{
      icon.removeClass('fa-angle-right');
      icon.addClass('fa-angle-down');
      notice_content.removeClass('dispaly-none');
      notice_content.addClass('opened');
    }
  });

  if ("<%= @has_alert %>" === 'true') {
    $('#alert-notice').modal('show');
  }

  new Clipboard('.btn');
  $('.show-md5-password').on('click', function(){
    $(this).addClass('dispaly-none');
    $('.md5-password-area').removeClass('dispaly-none');
  });

  $('.hide-md5-password').on('click', function(){
    $('.md5-password-area').addClass('dispaly-none');
    $('.show-md5-password').removeClass('dispaly-none');
  });

</script>

app/views/infos/l_infos.html.erb
<div class="col-md-12">
    <div class="box">
      <div class="box-header with-border">
        <h3 class="box-title">下级会员</h3>
      </div>
      <div class="box-body">
        <table class="table table-bordered">
          <tr>
            <th>昵称</th>
            <th>邮箱</th>
            <th>总提成</th>
            <th>提成记录</th>
          </tr>
          <% @l_users.each do |user| %>
            <tr>
              <td><%= user.name %></td>
              <td><%= user.email %></td>
              <td><%= current_user.deduct_percentage_form_user(user.id) %></td>
              <td>
                <%= link_to '提成记录', deduct_percentages_path(user_id: user.id) %>
                <%= link_to '特价', h_set_prices_path(user_id: user.id) %>
              </td>
            </tr>
          <% end %>
        </table>
      </div>
      <div class="box-footer clearfix">
        <ul class="pagination pagination-sm inline">
        </ul>
      </div>
    </div>
</div>